apiVersion: v1
kind: Secret
metadata:
  name: meridian-secret
  namespace: meridian
  labels:
    app.kubernetes.io/name: meridian-stream
    app.kubernetes.io/part-of: meridian
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
